server.port=8080

spring.profiles.active=dev

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:chatdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.security.jwt.secret=VGhpc0lzQVNlY3JldEtleUZvck9yYnlDaGF0QXBwMTIzNA==
app.security.jwt.expiration-seconds=3600
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# WhatsApp Meta API Configuration
whatsapp.api.url=https://graph.facebook.com/v25.0
whatsapp.phone.number.id=1072263239312245
whatsapp.api.token=EAAOnNDuUnGEBRcpNCNBKl1uB8sDu9evRjHC1XZA8ESbfZB3feTBesGAwjcrwxSQ7NKoZCzhORhk9vqovycFP2yOW19UV4aHvrjHfdeDMsL8VylP9IlYMp7uMmZAZAqVQfcUs1HxHoUWjfLugJX0BKSYWJBzJiLmw96wtyMsySgwZCBdtdSnXCjgGRI4pV7sOgy3wZDZD
whatsapp.verify.token=orby_verify_token

