server.port=8080

spring.profiles.active=dev

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:chatdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.security.jwt.secret=VGhpc0lzQVNlY3JldEtleUZvck9yYnlDaGF0QXBwMTIzNA==
app.security.jwt.expiration-seconds=3600
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# WhatsApp Meta API Configuration
whatsapp.api.url=https://graph.facebook.com/v25.0
whatsapp.phone.number.id=1072263239312245
whatsapp.api.token=EAAOnNDuUnGEBRVTeKZBZC7h34kJbzypBqrlt8v8GI10jX1SZCSlx9GUy6b0E99ucGgYuSaBR9itnkRco09qDifY1v5KKH3dSYKknI09Mcvsgsmr98Rb7Fle27uC1cZAoA990kUMdrZBU0Pa5ZBLgZBJtZAgt2wdGhBSV1dXaG08lMynMVJ5ZBdDwzNUeqHxazjHzfXMPkmZApYsZCweBhpVD6JIKxk6szvDp6oNMGwUAyadJrYBkSgJnsRwaIEJM3yLZCHPojoPncfXgHZAJdA6CPfSXmPpWX14IZD
whatsapp.verify.token=orby_verify_token

