server.port=8080

spring.profiles.active=dev

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:chatdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.security.jwt.secret=VGhpc0lzQVNlY3JldEtleUZvck9yYnlDaGF0QXBwMTIzNA==
app.security.jwt.expiration-seconds=3600
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# WhatsApp Meta API Configuration
whatsapp.api.url=https://graph.facebook.com/v25.0
whatsapp.phone.number.id=1072263239312245
whatsapp.api.token=EAAOnNDuUnGEBRSzYPPoMCPFEAgJXmcf3mZAmf0SUvyZC1XVXAQOxTRuZCSa7abOTmFCJDkZBOI2IG8SN3v6OWZCBDSwPlyJNyV61OHZCCCuZCzFIVoSnot069hu7XSnKZARwAja4x3u5pAmd8Tgj7DU8SXkBJyQn4Nw9SxlqmyZAabfXyK76ZBp8LHc96TwuL64YYzuWJ3nHwY8dAxVIDFD1QARXXdYeB1H1c1YZAFoC7axGNECmcZCfOtHckc4ZBzdKMzyXuy995ruo7ij7uTffea6Dj3oLVRGcZD
whatsapp.verify.token=orby_verify_token

